// docs/components/table-page/basic/index.vue
<script lang="ts" setup>
import {ref} from 'vue'
import {TablePageProps} from '../../../../packages'

interface DataProps {
    date: string;
    name: string;
    address: string;
}


const tablePage = ref<TablePageProps<DataProps, DataProps, DataProps>>({
    table: {
        pagination: {
        },
        tableColumns: [
            {
                type: 'selection',
            },
            {
                prop: 'date',
                label: '时间'
            },
            {
                prop: 'name',
                label: '名称',
                sort: 1
            },
            {
                prop: 'address',
                label: '地址'
            },
        ],
        data: [
            {
                date: '2016-05-03',
                name: 'Tom',
                address: '广州市区',
            },
            {
                date: '2016-05-02',
                name: 'Tom',
                address: '广州市区',
            },
            {
                date: '2016-05-04',
                name: 'Tom',
                address: '广州市区',
            },
            {
                date: '2016-05-01',
                name: 'Tom',
                address: '广州市区',
            },
        ]
    },
    form: {
        model: {},
        formItem: {
            name: {
                type: 'input',
                label: '名称',
                options: {}
            },
            address: {
                type: 'input',
                label: '地址',
                options: {}
            },
            date: {
                type: 'date',
                label: '时间',
                options: {}
            },
        }
    },
    footer: true
})

const search = () => {
    console.log('查询')
}

const reset = () => {
    console.log('重置')
}

const checkedChange = () => {
    console.log('fdsafa')
}

const sizeChange = () => {
    console.log('fdsafa')
}

const currentChange = () => {
    console.log('fdsafa')
}
</script>

<template>
    <dinert-table-page :table="tablePage.table" :form="tablePage.form"
        class="near"
        :footer="tablePage.footer"
        @search-fn="search"
        @reset-fn="reset"
        @checked-change="checkedChange"
        @size-change="sizeChange"
        @current-change="currentChange"
    />
</template>

// docs/components/table-page/basic/index.tsx
import React, { useState } from 'react'

import {DinertTablePage, TablePageProps} from '../../../../packages'

function App() {
    const [stateTablePage] = useState<TablePageProps>({
        form: {
            formItem: {
                name: {
                    label: '名称',
                    type: 'input',
                    options: {}
                },
                status: {
                    label: '状态',
                    type: 'select',
                    options: {
                        options: [
                            {value: true, label: '启用'},
                            {value: false, label: '禁用'},
                        ]
                    }
                }
            },
            initialValues: {}
        },
        table: {
            rowSelection: {
            },
            tableLayout: 'fixed',
            rowKey: 'date',
            dataSource: [
                {
                    date: '2016-05-03',
                    name: 'Tom',
                    address: '广州市区',
                },
                {
                    date: '2016-05-02',
                    name: 'Tom',
                    address: '广州市区',
                },
                {
                    date: '2016-05-04',
                    name: 'Tom',
                    address: '广州市区',
                },
                {
                    date: '2016-05-01',
                    name: 'Tom',
                    address: '广州市区',
                },
            ],
            tableColumns: [

                {
                    dataIndex: 'date',
                    title: '时间'
                },
                {
                    dataIndex: 'name',
                    title: '名称',
                },
                {
                    dataIndex: 'address',
                    title: '地址'
                },
            ]
        }

    })

    return (
        <DinertTablePage {...stateTablePage}>

        </DinertTablePage>
    )
}

export default App
